"""rename address

Revision ID: 5643eecea4e3
Revises: f1f8be3adc85
Create Date: 2024-10-01 22:58:03.510170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5643eecea4e3'
down_revision = 'f1f8be3adc85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
